# Generated by Django 5.0 on 2024-04-12 15:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
